### ISSUE TITLE
Released artifact does not function properly.

### ISSUE THREAD

**Issue by EmilLa1** [Concordium/concordium-java-sdk#290]
**Bug Description**

Beginning from version 6.0.0 we started to publish artifacts as part of the release process.
The artifact (without embedded dependencies) does not function properly when installing it into ones local maven repository as the transitive dependencies are not resolved. (The `concordium-x.y.z-jar-with-dependencies.jar` works however)

**Steps to Reproduce**

1. Download an artifact from the release page. https://github.com/Concordium/concordium-java-sdk/releases/tag/v.6.0.0
2. Install it into the local maven repository e.g.,

```
mvn install:install-file -Dfile=/path/to/Downloads/concordium-sdk-6.0.0.jar -DgroupId=com.concordium.sdk -DartifactId=concordium-sdk -Dversion=6.0.0 -Dpackaging=jar

```

3. Setup a new maven project and add the newly installed dependency 
```
 <dependency>
            <groupId>com.concordium.sdk</groupId>
            <artifactId>concordium-sdk-jar-with-dependencies</artifactId>
            <version>6.0.0</version>
            <scope>compile</scope>
        </dependency>
```

4. and a simple endpoint which uses the SDK: 

```
public class Main {
    public static void main(String[] args)  {
        try {
            ClientV2 client =   ClientV2 client = ClientV2.from(Connection.newBuilder().host("localhost").port(20000).build());
            BlockInfo blockInfo = client.getBlockInfo(BlockQuery.BEST);
            System.out.println(blockInfo);
            System.out.println("Hello world!");
        }catch (Exception e) {
            e.printStackTrace();
        }

    }
}
```
**Expected Result**

```
 BlockInfo(transactionEnergyCost=495, blockBaker=84885, blockStateHash=efbb8336bba285256937e2f29a98b3805b4827508ad8a3557b3a634066069f98, blockTime=2023-12-14T12:24:01.332Z[UTC], blockParent=7a2b8cf089653caedb7e2d3b0530930bd652e4bd0912f0d3878d47eb182ed363, blockReceiveTime=2023-12-14T12:24:01.473Z[UTC], genesisIndex=5, blockSlot=0, finalized=false, eraBlockHeight=3257024, blockLastFinalized=e724411622816e17af90a17382e7dcfeea72e8d13d9a08f29d97817f92e462b0, transactionsSize=166, transactionCount=1, blockArriveTime=2023-12-14T12:24:01.481Z[UTC], protocolVersion=V6, round=Optional[Round(value=3304412)], epoch=Optional[Epoch(value=1923)])
Hello world!

```

**Actual Result**

```
Exception in thread "main" java.lang.NoClassDefFoundError: io/grpc/StatusRuntimeException
	at org.example.Main.main(Main.java:13)
Caused by: java.lang.ClassNotFoundException: io.grpc.StatusRuntimeException
	at java.net.URLClassLoader.findClass(URLClassLoader.java:387)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 1 more
```

## Workaround
Use the `concordium-sdk-6.0.0-jar-with-dependencies.jar` library.

**Comment by EmilLa1** [comment]
No longer relevant as the jar is now published to the maven central and thus the transitive dependencies can be resolved. https://github.com/Concordium/concordium-java-sdk/pull/303
